# Generated by Django 2.1.2 on 2019-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
                ('service_category', models.CharField(max_length=200)),
                ('service_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_contact', models.IntegerField(default=0)),
                ('staff_address', models.CharField(max_length=200)),
            ],
        ),
    ]
