# Generated by Django 2.1.2 on 2019-04-08 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0003_auto_20190404_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smanager.Customer')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smanager.Services')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smanager.Staff')),
            ],
        ),
    ]
