# Generated by Django 2.1.2 on 2019-04-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0004_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
