# Generated by Django 2.1.2 on 2019-04-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smanager', '0005_auto_20190408_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
